manifest:
  remotes:
      # zmk official
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
      # bravekarma
    - name: urchin
      url-base: https://github.com/antrodroid
  projects:
    - name: zmk
      remote: urchin
      revision: main
      import: app/west.yml
    - name: zmk-helpers
      remote: urchin
      revision: v2
  self:
    path: config
